### ISSUE TITLE
cannot restart sway/tools without breaking things

### ISSUE THREAD

**Issue by eoli3n** [ifreund/dumb_runtime_dir#4] opened 2022-09-16 08:36 UTC
I dropped pam_rundir on void with seatd because I was not able to restart a sway session (autostarted on tty1).
With dumb_runtime_dir, I can, but pipewire and sway breaks is some ways.

- At first session, everything works properly : that's good.

- If I ``swaymsg exit`` and I login on tty1, pipewire start but no inputs/outputs, and sway notifications breaks with an error.
```
Failed to invoke on-highlight command at path: exit status 1. Output: "00:00:00.000 [ERROR] [common/ipc-client.c:67] Unable to connect to/run/user/1000/sway-ipc.1000.6032.sock
```
The file doesn't exist.

- If I ``swaymsg exit``, with root ``rm -rf /run/user/1000``, login back, then pipewire refuse to start completely, and sway notification are not working, but without any error message.

What am I missing ?

Is there a way to add a cleanup at session close, to be able to logout/login properly without needing for tools to handle this properly ?

**Comment by ifreund** [comment] 2022-09-16 10:54
Correct programs must handle the existence of files in `$XDG_RUNTIME_DIR` as the spec states that the same directory is used for multiple simultaneous sessions. I don't know why sway/pipewire aren't working for you but river + pipewire work fine for me.

`dumb_runtime_dir` is 100% feature complete and works as intended. I won't be adding any cleanup at last session close as not having that complexity is the entire point of this software.

**Closed as completed by ifreund** 2022-09-16 10:54 UTC

**Comment by Zapeth** [comment] 2023-10-27 15:25
> Correct programs must handle the existence of files in $XDG_RUNTIME_DIR as the spec states that the same directory is used for multiple simultaneous sessions.

As far as I can tell the issue is not about simultaneous sessions, but successive ones. And for those the spec explicitly states that the directory with all its contents must be removed on last logout (which doesn't happen in this module).

**Comment by ifreund** [comment] 2023-10-27 16:13
> As far as I can tell the issue is not about simultaneous sessions, but successive ones. And for those the spec explicitly states that the directory with all its contents must be removed on last logout (which doesn't happen in this module).

Indeed, and this is an intentional design choice:

> Creates an XDG_RUNTIME_DIR directory on login per the freedesktop.org base directory spec. Flaunts the spec and never removes it, even after last logout.

If dumb_runtime_dir doesn't work for you I suggest using one of the other solutions to this problem.

**Comment by Zapeth** [comment] 2023-10-27 16:27
Fair enough, I guess you already have it explicitly stated in the README, but it might still be worth pointing out that some applications could have issues with this design choice (eg as described in this issue).

Anyway its just meant as suggestion, so feel free to ignore it.
